-- Students table
CREATE TABLE IF NOT EXISTS "students" (
  "sid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
  "first" VARCHAR NOT NULL,
  "last" VARCHAR NOT NULL);

-- Quizzes table
CREATE TABLE IF NOT EXISTS "quizzes" (
  "qid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
  "date" DATETIME NOT NULL ,
  "subj" VARCHAR NOT NULL ,
  "numq" VARCHAR NOT NULL );

-- Results table
CREATE TABLE IF NOT EXISTS "results" (
  "rid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
  "sid" INTEGER NOT NULL ,
  "qid" INTEGER NOT NULL ,
  "score" FLOAT);
